// <auto-generated />
using CommandAPISolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommandAPISolution.Migrations
{
    [DbContext(typeof(CommandContext))]
    [Migration("20211120055749_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommandAPI.Models.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommandItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommandLine = "dotnet ef migrations add <Name of Migration>",
                            HowTo = "How to generete migration",
                            Platform = ".Net Core Ef"
                        },
                        new
                        {
                            Id = 2,
                            CommandLine = "dotnet ef database update",
                            HowTo = "Run Migrations",
                            Platform = ".Net Core Ef"
                        },
                        new
                        {
                            Id = 3,
                            CommandLine = "dotnet ef migrations list",
                            HowTo = "List active migrations",
                            Platform = ".Net Core Ef"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
